/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.daemon.Fprintd.Device.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Fprintd.DeviceAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Fprintd.Device.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Fprintd.DeviceAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DeviceAdaptor
 */

DeviceAdaptor::DeviceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DeviceAdaptor::~DeviceAdaptor()
{
    // destructor
}

void DeviceAdaptor::Claim(const QString &in0)
{
    // handle method call com.deepin.daemon.Fprintd.Device.Claim
    QMetaObject::invokeMethod(parent(), "Claim", Q_ARG(QString, in0));
}

void DeviceAdaptor::DeleteEnrolledFingers(const QString &in0)
{
    // handle method call com.deepin.daemon.Fprintd.Device.DeleteEnrolledFingers
    QMetaObject::invokeMethod(parent(), "DeleteEnrolledFingers", Q_ARG(QString, in0));
}

void DeviceAdaptor::EnrollStart(const QString &in0)
{
    // handle method call com.deepin.daemon.Fprintd.Device.EnrollStart
    QMetaObject::invokeMethod(parent(), "EnrollStart", Q_ARG(QString, in0));
}

void DeviceAdaptor::EnrollStop()
{
    // handle method call com.deepin.daemon.Fprintd.Device.EnrollStop
    QMetaObject::invokeMethod(parent(), "EnrollStop");
}

QStringList DeviceAdaptor::ListEnrolledFingers(const QString &in0)
{
    // handle method call com.deepin.daemon.Fprintd.Device.ListEnrolledFingers
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "ListEnrolledFingers", Q_RETURN_ARG(QStringList, out0), Q_ARG(QString, in0));
    return out0;
}

void DeviceAdaptor::Release()
{
    // handle method call com.deepin.daemon.Fprintd.Device.Release
    QMetaObject::invokeMethod(parent(), "Release");
}

void DeviceAdaptor::VerifyStart(const QString &in0)
{
    // handle method call com.deepin.daemon.Fprintd.Device.VerifyStart
    QMetaObject::invokeMethod(parent(), "VerifyStart", Q_ARG(QString, in0));
}

void DeviceAdaptor::VerifyStop()
{
    // handle method call com.deepin.daemon.Fprintd.Device.VerifyStop
    QMetaObject::invokeMethod(parent(), "VerifyStop");
}

