/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.daemon.Timedate.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.TimedateAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Timedate.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.TimedateAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TimedateAdaptor
 */

TimedateAdaptor::TimedateAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TimedateAdaptor::~TimedateAdaptor()
{
    // destructor
}

bool TimedateAdaptor::canNTP() const
{
    // get the value of property CanNTP
    return qvariant_cast< bool >(parent()->property("CanNTP"));
}

int TimedateAdaptor::dSTOffset() const
{
    // get the value of property DSTOffset
    return qvariant_cast< int >(parent()->property("DSTOffset"));
}

void TimedateAdaptor::setDSTOffset(int value)
{
    // set the value of property DSTOffset
    parent()->setProperty("DSTOffset", QVariant::fromValue(value));
}

bool TimedateAdaptor::localRTC() const
{
    // get the value of property LocalRTC
    return qvariant_cast< bool >(parent()->property("LocalRTC"));
}

int TimedateAdaptor::longDateFormat() const
{
    // get the value of property LongDateFormat
    return qvariant_cast< int >(parent()->property("LongDateFormat"));
}

void TimedateAdaptor::setLongDateFormat(int value)
{
    // set the value of property LongDateFormat
    parent()->setProperty("LongDateFormat", QVariant::fromValue(value));
}

int TimedateAdaptor::longTimeFormat() const
{
    // get the value of property LongTimeFormat
    return qvariant_cast< int >(parent()->property("LongTimeFormat"));
}

void TimedateAdaptor::setLongTimeFormat(int value)
{
    // set the value of property LongTimeFormat
    parent()->setProperty("LongTimeFormat", QVariant::fromValue(value));
}

bool TimedateAdaptor::nTP() const
{
    // get the value of property NTP
    return qvariant_cast< bool >(parent()->property("NTP"));
}

QString TimedateAdaptor::nTPServer() const
{
    // get the value of property NTPServer
    return qvariant_cast< QString >(parent()->property("NTPServer"));
}

int TimedateAdaptor::shortDateFormat() const
{
    // get the value of property ShortDateFormat
    return qvariant_cast< int >(parent()->property("ShortDateFormat"));
}

void TimedateAdaptor::setShortDateFormat(int value)
{
    // set the value of property ShortDateFormat
    parent()->setProperty("ShortDateFormat", QVariant::fromValue(value));
}

int TimedateAdaptor::shortTimeFormat() const
{
    // get the value of property ShortTimeFormat
    return qvariant_cast< int >(parent()->property("ShortTimeFormat"));
}

void TimedateAdaptor::setShortTimeFormat(int value)
{
    // set the value of property ShortTimeFormat
    parent()->setProperty("ShortTimeFormat", QVariant::fromValue(value));
}

QString TimedateAdaptor::timezone() const
{
    // get the value of property Timezone
    return qvariant_cast< QString >(parent()->property("Timezone"));
}

bool TimedateAdaptor::use24HourFormat() const
{
    // get the value of property Use24HourFormat
    return qvariant_cast< bool >(parent()->property("Use24HourFormat"));
}

void TimedateAdaptor::setUse24HourFormat(bool value)
{
    // set the value of property Use24HourFormat
    parent()->setProperty("Use24HourFormat", QVariant::fromValue(value));
}

QStringList TimedateAdaptor::userTimezones() const
{
    // get the value of property UserTimezones
    return qvariant_cast< QStringList >(parent()->property("UserTimezones"));
}

int TimedateAdaptor::weekBegins() const
{
    // get the value of property WeekBegins
    return qvariant_cast< int >(parent()->property("WeekBegins"));
}

void TimedateAdaptor::setWeekBegins(int value)
{
    // set the value of property WeekBegins
    parent()->setProperty("WeekBegins", QVariant::fromValue(value));
}

int TimedateAdaptor::weekdayFormat() const
{
    // get the value of property WeekdayFormat
    return qvariant_cast< int >(parent()->property("WeekdayFormat"));
}

void TimedateAdaptor::setWeekdayFormat(int value)
{
    // set the value of property WeekdayFormat
    parent()->setProperty("WeekdayFormat", QVariant::fromValue(value));
}

void TimedateAdaptor::AddUserTimezone(const QString &in0)
{
    // handle method call com.deepin.daemon.Timedate.AddUserTimezone
    QMetaObject::invokeMethod(parent(), "AddUserTimezone", Q_ARG(QString, in0));
}

void TimedateAdaptor::DeleteUserTimezone(const QString &in0)
{
    // handle method call com.deepin.daemon.Timedate.DeleteUserTimezone
    QMetaObject::invokeMethod(parent(), "DeleteUserTimezone", Q_ARG(QString, in0));
}

QStringList TimedateAdaptor::GetSampleNTPServers()
{
    // handle method call com.deepin.daemon.Timedate.GetSampleNTPServers
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "GetSampleNTPServers", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

ZoneInfo TimedateAdaptor::GetZoneInfo(const QString &in0)
{
    // handle method call com.deepin.daemon.Timedate.GetZoneInfo
    ZoneInfo out0;
    QMetaObject::invokeMethod(parent(), "GetZoneInfo", Q_RETURN_ARG(ZoneInfo, out0), Q_ARG(QString, in0));
    return out0;
}

QStringList TimedateAdaptor::GetZoneList()
{
    // handle method call com.deepin.daemon.Timedate.GetZoneList
    QStringList out0;
    QMetaObject::invokeMethod(parent(), "GetZoneList", Q_RETURN_ARG(QStringList, out0));
    return out0;
}

void TimedateAdaptor::SetDate(int in0, int in1, int in2, int in3, int in4, int in5, int in6)
{
    // handle method call com.deepin.daemon.Timedate.SetDate
    QMetaObject::invokeMethod(parent(), "SetDate", Q_ARG(int, in0), Q_ARG(int, in1), Q_ARG(int, in2), Q_ARG(int, in3), Q_ARG(int, in4), Q_ARG(int, in5), Q_ARG(int, in6));
}

void TimedateAdaptor::SetLocalRTC(bool in0, bool in1)
{
    // handle method call com.deepin.daemon.Timedate.SetLocalRTC
    QMetaObject::invokeMethod(parent(), "SetLocalRTC", Q_ARG(bool, in0), Q_ARG(bool, in1));
}

void TimedateAdaptor::SetNTP(bool in0)
{
    // handle method call com.deepin.daemon.Timedate.SetNTP
    QMetaObject::invokeMethod(parent(), "SetNTP", Q_ARG(bool, in0));
}

void TimedateAdaptor::SetNTPServer(const QString &in0)
{
    // handle method call com.deepin.daemon.Timedate.SetNTPServer
    QMetaObject::invokeMethod(parent(), "SetNTPServer", Q_ARG(QString, in0));
}

void TimedateAdaptor::SetTime(qlonglong in0, bool in1)
{
    // handle method call com.deepin.daemon.Timedate.SetTime
    QMetaObject::invokeMethod(parent(), "SetTime", Q_ARG(qlonglong, in0), Q_ARG(bool, in1));
}

void TimedateAdaptor::SetTimezone(const QString &in0)
{
    // handle method call com.deepin.daemon.Timedate.SetTimezone
    QMetaObject::invokeMethod(parent(), "SetTimezone", Q_ARG(QString, in0));
}

