/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.daemon.ImageEffect.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.ImageEffectAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.ImageEffect.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DAEMON_IMAGEEFFECTADAPTOR_H
#define COM_DEEPIN_DAEMON_IMAGEEFFECTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.ImageEffect.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.daemon.ImageEffect
 */
class ImageEffectAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.daemon.ImageEffect")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.daemon.ImageEffect\">\n"
"    <method name=\"Delete\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"effect\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\"/>\n"
"    </method>\n"
"    <method name=\"Get\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"effect\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"filename\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"outputFile\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    ImageEffectAdaptor(QObject *parent);
    virtual ~ImageEffectAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Delete(const QString &effect, const QString &filename);
    QString Get(const QString &effect, const QString &filename);
Q_SIGNALS: // SIGNALS
};

#endif
