/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.daemon.SoundEffect.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.SoundEffectAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.SoundEffect.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DAEMON_SOUNDEFFECTADAPTOR_H
#define COM_DEEPIN_DAEMON_SOUNDEFFECTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.SoundEffect.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.daemon.SoundEffect
 */
class SoundEffectAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.daemon.SoundEffect")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.daemon.SoundEffect\">\n"
"    <method name=\"EnableSound\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"GetSoundEnabledMap\">\n"
"      <arg direction=\"out\" type=\"a{sb}\" name=\"result\"/>\n"
"      <annotation value=\"QMap&lt;QString,bool&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"GetSoundFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"file\"/>\n"
"    </method>\n"
"    <method name=\"GetSystemSoundFile\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"file\"/>\n"
"    </method>\n"
"    <method name=\"IsSoundEnabled\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"enabled\"/>\n"
"    </method>\n"
"    <method name=\"PlaySound\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <method name=\"PlaySystemSound\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"    </method>\n"
"    <property access=\"readwrite\" type=\"b\" name=\"Enabled\"/>\n"
"  </interface>\n"
        "")
public:
    SoundEffectAdaptor(QObject *parent);
    virtual ~SoundEffectAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool Enabled READ enabled WRITE setEnabled)
    bool enabled() const;
    void setEnabled(bool value);

public Q_SLOTS: // METHODS
    void EnableSound(const QString &name, bool enabled);
    QMap<QString,bool> GetSoundEnabledMap();
    QString GetSoundFile(const QString &name);
    QString GetSystemSoundFile(const QString &name);
    bool IsSoundEnabled(const QString &name);
    void PlaySound(const QString &name);
    void PlaySystemSound(const QString &name);
Q_SIGNALS: // SIGNALS
};

#endif
