/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.iflytek.aiservice.iat.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.iatAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.iat.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_IFLYTEK_AISERVICE_IATADAPTOR_H
#define COM_IFLYTEK_AISERVICE_IATADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.iat.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.iflytek.aiservice.iat
 */
class IatAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.iflytek.aiservice.iat")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.iflytek.aiservice.iat\">\n"
"    <method name=\"startIat\">\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"param\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"status\"/>\n"
"    </method>\n"
"    <method name=\"putAudio\">\n"
"      <arg direction=\"in\" type=\"ay\" name=\"audio_buf\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"finish\"/>\n"
"    </method>\n"
"    <method name=\"stopIat\"/>\n"
"    <signal name=\"onResult\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"result\"/>\n"
"    </signal>\n"
"    <signal name=\"onError\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"errInfo\"/>\n"
"    </signal>\n"
"    <signal name=\"onEnd\"/>\n"
"  </interface>\n"
        "")
public:
    IatAdaptor(QObject *parent);
    virtual ~IatAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void putAudio(const QByteArray &audio_buf, bool finish);
    QString startIat(const QVariantMap &param);
    void stopIat();
Q_SIGNALS: // SIGNALS
    void onEnd();
    void onError(const QString &errInfo);
    void onResult(const QString &result);
};

#endif
