/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.sync.daemon.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.sync.daemonAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.sync.daemon.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_SYNC_DAEMONADAPTOR_H
#define COM_DEEPIN_SYNC_DAEMONADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.sync.daemon.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.sync.Daemon
 */
class DaemonAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.sync.Daemon")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.sync.Daemon\">\n"
"    <method name=\"IsOnline\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"OnMessage\">\n"
"      <arg direction=\"in\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </method>\n"
"    <method name=\"Register\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"SwitcherDump\">\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"SwitcherGet\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"SwitcherSet\">\n"
"      <arg direction=\"in\" type=\"s\"/>\n"
"      <arg direction=\"in\" type=\"b\"/>\n"
"    </method>\n"
"    <signal name=\"SwitcherChange\">\n"
"      <arg type=\"s\" name=\"switcher\"/>\n"
"      <arg type=\"b\" name=\"enabled\"/>\n"
"    </signal>\n"
"    <property access=\"read\" type=\"x\" name=\"LastSyncTime\"/>\n"
"    <property access=\"read\" type=\"(is)\" name=\"State\">\n"
"      <annotation value=\"IntString\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"    <property access=\"read\" type=\"a{sv}\" name=\"UserInfo\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
"    </property>\n"
"  </interface>\n"
        "")
public:
    DaemonAdaptor(QObject *parent);
    virtual ~DaemonAdaptor();

public: // PROPERTIES
    Q_PROPERTY(qlonglong LastSyncTime READ lastSyncTime)
    qlonglong lastSyncTime() const;

    Q_PROPERTY(IntString State READ state)
    IntString state() const;

    Q_PROPERTY(QVariantMap UserInfo READ userInfo)
    QVariantMap userInfo() const;

public Q_SLOTS: // METHODS
    bool IsOnline();
    void OnMessage(const QVariantMap &in0);
    void Register(const QString &in0, const QString &in1);
    QString SwitcherDump();
    bool SwitcherGet(const QString &in0);
    void SwitcherSet(const QString &in0, bool in1);
Q_SIGNALS: // SIGNALS
    void SwitcherChange(const QString &switcher, bool enabled);
};

#endif
