/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.iflytek.aiservice.asr.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.asrAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.asr.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_IFLYTEK_AISERVICE_ASRADAPTOR_H
#define COM_IFLYTEK_AISERVICE_ASRADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.asr.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.iflytek.aiservice.asr
 */
class AsrAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.iflytek.aiservice.asr")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.iflytek.aiservice.asr\">\n"
"    <method name=\"startAsr\">\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"param\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"code\"/>\n"
"    </method>\n"
"    <method name=\"stopAsr\"/>\n"
"    <signal name=\"onNotify\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"msg\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    AsrAdaptor(QObject *parent);
    virtual ~AsrAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString startAsr(const QVariantMap &param);
    void stopAsr();
Q_SIGNALS: // SIGNALS
    void onNotify(const QString &msg);
};

#endif
