/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.defender.netcontrol.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.defender.netcontrolAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.defender.netcontrol.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.defender.netcontrolAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class NetcontrolAdaptor
 */

NetcontrolAdaptor::NetcontrolAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

NetcontrolAdaptor::~NetcontrolAdaptor()
{
    // destructor
}

double NetcontrolAdaptor::globalRecv() const
{
    // get the value of property globalRecv
    return qvariant_cast< double >(parent()->property("globalRecv"));
}

bool NetcontrolAdaptor::quitDefender() const
{
    // get the value of property quitDefender
    return qvariant_cast< bool >(parent()->property("quitDefender"));
}

void NetcontrolAdaptor::setQuitDefender(bool value)
{
    // set the value of property quitDefender
    parent()->setProperty("quitDefender", QVariant::fromValue(value));
}

void NetcontrolAdaptor::ExitApp()
{
    // handle method call com.deepin.defender.netcontrol.ExitApp
    QMetaObject::invokeMethod(parent(), "ExitApp");
}

void NetcontrolAdaptor::StartApp()
{
    // handle method call com.deepin.defender.netcontrol.StartApp
    QMetaObject::invokeMethod(parent(), "StartApp");
}

int NetcontrolAdaptor::getConnCunrrentIndex()
{
    // handle method call com.deepin.defender.netcontrol.getConnCunrrentIndex
    int value;
    QMetaObject::invokeMethod(parent(), "getConnCunrrentIndex", Q_RETURN_ARG(int, value));
    return value;
}

int NetcontrolAdaptor::getRemCunrrentIndex()
{
    // handle method call com.deepin.defender.netcontrol.getRemCunrrentIndex
    int value;
    QMetaObject::invokeMethod(parent(), "getRemCunrrentIndex", Q_RETURN_ARG(int, value));
    return value;
}

void NetcontrolAdaptor::preInitialize()
{
    // handle method call com.deepin.defender.netcontrol.preInitialize
    QMetaObject::invokeMethod(parent(), "preInitialize");
}

void NetcontrolAdaptor::setColor(const QString &sColor)
{
    // handle method call com.deepin.defender.netcontrol.setColor
    QMetaObject::invokeMethod(parent(), "setColor", Q_ARG(QString, sColor));
}

void NetcontrolAdaptor::setConnCunrrentIndex(int index)
{
    // handle method call com.deepin.defender.netcontrol.setConnCunrrentIndex
    QMetaObject::invokeMethod(parent(), "setConnCunrrentIndex", Q_ARG(int, index));
}

void NetcontrolAdaptor::setRemCunrrentIndex(int index)
{
    // handle method call com.deepin.defender.netcontrol.setRemCunrrentIndex
    QMetaObject::invokeMethod(parent(), "setRemCunrrentIndex", Q_ARG(int, index));
}

void NetcontrolAdaptor::showFuncConnectNetControlInter(const QString &appNamePath)
{
    // handle method call com.deepin.defender.netcontrol.showFuncConnectNetControlInter
    QMetaObject::invokeMethod(parent(), "showFuncConnectNetControlInter", Q_ARG(QString, appNamePath));
}

void NetcontrolAdaptor::showRemConnectRemControlInter(const QString &appNamePath)
{
    // handle method call com.deepin.defender.netcontrol.showRemConnectRemControlInter
    QMetaObject::invokeMethod(parent(), "showRemConnectRemControlInter", Q_ARG(QString, appNamePath));
}

void NetcontrolAdaptor::test()
{
    // handle method call com.deepin.defender.netcontrol.test
    QMetaObject::invokeMethod(parent(), "test");
}

