/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.daemon.ResourceManager.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.ResourceManagerAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.ResourceManager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DAEMON_RESOURCEMANAGERADAPTOR_H
#define COM_DEEPIN_DAEMON_RESOURCEMANAGERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.ResourceManager.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.daemon.ResourceManager
 */
class ResourceManagerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.daemon.ResourceManager")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.daemon.ResourceManager\">\n"
"    <method name=\"Subscribe\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"pid\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"cmd\"/>\n"
"      <arg direction=\"in\" type=\"ai\" name=\"interest\"/>\n"
"      <annotation value=\"QList &lt;int &gt;\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"force\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"uuid\"/>\n"
"    </method>\n"
"    <method name=\"SubscribeControl\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"pid\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"cmd\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"ai\" name=\"interest\"/>\n"
"      <annotation value=\"QList &lt;int &gt;\" name=\"org.qtproject.QtDBus.QtTypeName.In3\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"uuid\"/>\n"
"    </method>\n"
"    <method name=\"Unsubscribe\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"uuid\"/>\n"
"    </method>\n"
"    <method name=\"AllowRequest\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"uuid\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"msg\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"allow\"/>\n"
"    </method>\n"
"    <signal name=\"Request\">\n"
"      <arg type=\"as\" name=\"subscribers\"/>\n"
"      <arg type=\"s\" name=\"msg\"/>\n"
"    </signal>\n"
"    <signal name=\"Notification\">\n"
"      <arg type=\"as\" name=\"subscribers\"/>\n"
"      <arg type=\"s\" name=\"msg\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    ResourceManagerAdaptor(QObject *parent);
    virtual ~ResourceManagerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void AllowRequest(const QString &uuid, const QString &msg, bool allow);
    QString Subscribe(int pid, const QString &cmd, const QList <int > &interest, bool force);
    QString SubscribeControl(int pid, const QString &cmd, const QString &name, const QList <int > &interest);
    void Unsubscribe(const QString &uuid);
Q_SIGNALS: // SIGNALS
    void Notification(const QStringList &subscribers, const QString &msg);
    void Request(const QStringList &subscribers, const QString &msg);
};

#endif
