/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.defender.autostart.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.defender.autostartAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.defender.autostart.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DEFENDER_AUTOSTARTADAPTOR_H
#define COM_DEEPIN_DEFENDER_AUTOSTARTADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.defender.autostart.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.defender.autostart
 */
class AutostartAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.defender.autostart")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.defender.autostart\">\n"
"    <property access=\"read\" type=\"d\" name=\"globalRecv\"/>\n"
"    <signal name=\"NotifyDetailData\">\n"
"      <arg type=\"s\" name=\"name\"/>\n"
"      <arg type=\"d\" name=\"recv\"/>\n"
"      <arg type=\"d\" name=\"send\"/>\n"
"      <arg type=\"i\" name=\"pid\"/>\n"
"      <arg type=\"s\" name=\"device\"/>\n"
"      <arg type=\"s\" name=\"type\"/>\n"
"    </signal>\n"
"    <signal name=\"NotifyGlobalData\">\n"
"      <arg type=\"d\" name=\"recv\"/>\n"
"      <arg type=\"d\" name=\"send\"/>\n"
"    </signal>\n"
"    <method name=\"StartApp\"/>\n"
"    <method name=\"ExitApp\"/>\n"
"    <signal name=\"NotifyHeartbeat\"/>\n"
"    <method name=\"preInitialize\"/>\n"
"    <method name=\"startLauncherManage\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"getAppsInfoEnable\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"getAppsInfoDisable\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"isAutostart\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"sPath\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"value\"/>\n"
"    </method>\n"
"    <method name=\"exeAutostart\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"nStatus\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"sPath\"/>\n"
"      <arg direction=\"out\" type=\"b\" name=\"value\"/>\n"
"    </method>\n"
"    <signal name=\"AccessRefreshData\">\n"
"      <arg type=\"b\" name=\"bAdd\"/>\n"
"      <arg type=\"s\" name=\"sID\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    AutostartAdaptor(QObject *parent);
    virtual ~AutostartAdaptor();

public: // PROPERTIES
    Q_PROPERTY(double globalRecv READ globalRecv)
    double globalRecv() const;

public Q_SLOTS: // METHODS
    void ExitApp();
    void StartApp();
    bool exeAutostart(int nStatus, const QString &sPath);
    QString getAppsInfoDisable();
    QString getAppsInfoEnable();
    bool isAutostart(const QString &sPath);
    void preInitialize();
    bool startLauncherManage();
Q_SIGNALS: // SIGNALS
    void AccessRefreshData(bool bAdd, const QString &sID);
    void NotifyDetailData(const QString &name, double recv, double send, int pid, const QString &device, const QString &type);
    void NotifyGlobalData(double recv, double send);
    void NotifyHeartbeat();
};

#endif
