/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.defender.autostart.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.defender.autostartAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.defender.autostart.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.defender.autostartAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AutostartAdaptor
 */

AutostartAdaptor::AutostartAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AutostartAdaptor::~AutostartAdaptor()
{
    // destructor
}

double AutostartAdaptor::globalRecv() const
{
    // get the value of property globalRecv
    return qvariant_cast< double >(parent()->property("globalRecv"));
}

void AutostartAdaptor::ExitApp()
{
    // handle method call com.deepin.defender.autostart.ExitApp
    QMetaObject::invokeMethod(parent(), "ExitApp");
}

void AutostartAdaptor::StartApp()
{
    // handle method call com.deepin.defender.autostart.StartApp
    QMetaObject::invokeMethod(parent(), "StartApp");
}

bool AutostartAdaptor::exeAutostart(int nStatus, const QString &sPath)
{
    // handle method call com.deepin.defender.autostart.exeAutostart
    bool value;
    QMetaObject::invokeMethod(parent(), "exeAutostart", Q_RETURN_ARG(bool, value), Q_ARG(int, nStatus), Q_ARG(QString, sPath));
    return value;
}

QString AutostartAdaptor::getAppsInfoDisable()
{
    // handle method call com.deepin.defender.autostart.getAppsInfoDisable
    QString value;
    QMetaObject::invokeMethod(parent(), "getAppsInfoDisable", Q_RETURN_ARG(QString, value));
    return value;
}

QString AutostartAdaptor::getAppsInfoEnable()
{
    // handle method call com.deepin.defender.autostart.getAppsInfoEnable
    QString value;
    QMetaObject::invokeMethod(parent(), "getAppsInfoEnable", Q_RETURN_ARG(QString, value));
    return value;
}

bool AutostartAdaptor::isAutostart(const QString &sPath)
{
    // handle method call com.deepin.defender.autostart.isAutostart
    bool value;
    QMetaObject::invokeMethod(parent(), "isAutostart", Q_RETURN_ARG(bool, value), Q_ARG(QString, sPath));
    return value;
}

void AutostartAdaptor::preInitialize()
{
    // handle method call com.deepin.defender.autostart.preInitialize
    QMetaObject::invokeMethod(parent(), "preInitialize");
}

bool AutostartAdaptor::startLauncherManage()
{
    // handle method call com.deepin.defender.autostart.startLauncherManage
    bool value;
    QMetaObject::invokeMethod(parent(), "startLauncherManage", Q_RETURN_ARG(bool, value));
    return value;
}

