/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.daemon.Miracast.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.MiracastAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Miracast.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.MiracastAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class MiracastAdaptor
 */

MiracastAdaptor::MiracastAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

MiracastAdaptor::~MiracastAdaptor()
{
    // destructor
}

void MiracastAdaptor::Connect(const QDBusObjectPath &in0, uint in1, uint in2, uint in3, uint in4)
{
    // handle method call com.deepin.daemon.Miracast.Connect
    QMetaObject::invokeMethod(parent(), "Connect", Q_ARG(QDBusObjectPath, in0), Q_ARG(uint, in1), Q_ARG(uint, in2), Q_ARG(uint, in3), Q_ARG(uint, in4));
}

void MiracastAdaptor::Disconnect(const QDBusObjectPath &in0)
{
    // handle method call com.deepin.daemon.Miracast.Disconnect
    QMetaObject::invokeMethod(parent(), "Disconnect", Q_ARG(QDBusObjectPath, in0));
}

void MiracastAdaptor::Enable(const QDBusObjectPath &in0, bool in1)
{
    // handle method call com.deepin.daemon.Miracast.Enable
    QMetaObject::invokeMethod(parent(), "Enable", Q_ARG(QDBusObjectPath, in0), Q_ARG(bool, in1));
}

LinkInfoList MiracastAdaptor::ListLinks()
{
    // handle method call com.deepin.daemon.Miracast.ListLinks
    LinkInfoList out0;
    QMetaObject::invokeMethod(parent(), "ListLinks", Q_RETURN_ARG(LinkInfoList, out0));
    return out0;
}

SinkInfoList MiracastAdaptor::ListSinks()
{
    // handle method call com.deepin.daemon.Miracast.ListSinks
    SinkInfoList out0;
    QMetaObject::invokeMethod(parent(), "ListSinks", Q_RETURN_ARG(SinkInfoList, out0));
    return out0;
}

void MiracastAdaptor::Scanning(const QDBusObjectPath &in0, bool in1)
{
    // handle method call com.deepin.daemon.Miracast.Scanning
    QMetaObject::invokeMethod(parent(), "Scanning", Q_ARG(QDBusObjectPath, in0), Q_ARG(bool, in1));
}

