/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.daemon.Calendar.Scheduler.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Calendar.SchedulerAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Calendar.Scheduler.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DAEMON_CALENDAR_SCHEDULERADAPTOR_H
#define COM_DEEPIN_DAEMON_CALENDAR_SCHEDULERADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Calendar.Scheduler.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.daemon.Calendar.Scheduler
 */
class SchedulerAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.daemon.Calendar.Scheduler")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.daemon.Calendar.Scheduler\">\n"
"    <method name=\"CreateJob\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"jobInfo\"/>\n"
"      <arg direction=\"out\" type=\"x\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"CreateType\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"typeInfo\"/>\n"
"      <arg direction=\"out\" type=\"x\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"DebugRemindJob\">\n"
"      <arg direction=\"in\" type=\"x\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"DeleteJob\">\n"
"      <arg direction=\"in\" type=\"x\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"DeleteType\">\n"
"      <arg direction=\"in\" type=\"x\" name=\"id\"/>\n"
"    </method>\n"
"    <method name=\"GetJob\">\n"
"      <arg direction=\"in\" type=\"x\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"job\"/>\n"
"    </method>\n"
"    <method name=\"GetJobs\">\n"
"      <arg direction=\"in\" type=\"i\" name=\"startYear\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"startMonth\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"startDay\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"endYear\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"endMonth\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"endDay\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"jobs\"/>\n"
"    </method>\n"
"    <method name=\"GetType\">\n"
"      <arg direction=\"in\" type=\"x\" name=\"id\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"type\"/>\n"
"    </method>\n"
"    <method name=\"GetTypes\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"types\"/>\n"
"    </method>\n"
"    <method name=\"UpdateJob\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"jobInfo\"/>\n"
"    </method>\n"
"    <method name=\"UpdateType\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"typeInfo\"/>\n"
"    </method>\n"
"    <signal name=\"JobsUpdated\">\n"
"      <arg type=\"ax\" name=\"Ids\"/>\n"
"      <annotation value=\"QList&lt;qlonglong&gt;\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    SchedulerAdaptor(QObject *parent);
    virtual ~SchedulerAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    qlonglong CreateJob(const QString &jobInfo);
    qlonglong CreateType(const QString &typeInfo);
    void DebugRemindJob(qlonglong id);
    void DeleteJob(qlonglong id);
    void DeleteType(qlonglong id);
    QString GetJob(qlonglong id);
    QString GetJobs(int startYear, int startMonth, int startDay, int endYear, int endMonth, int endDay);
    QString GetType(qlonglong id);
    QString GetTypes();
    void UpdateJob(const QString &jobInfo);
    void UpdateType(const QString &typeInfo);
Q_SIGNALS: // SIGNALS
    void JobsUpdated(const QList<qlonglong> &Ids);
};

#endif
