/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.iflytek.aiservice.session.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.sessionAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.session.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.sessionAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class SessionAdaptor
 */

SessionAdaptor::SessionAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

SessionAdaptor::~SessionAdaptor()
{
    // destructor
}

QDBusObjectPath SessionAdaptor::createSession(const QString &appId, const QString &ability, int &errorcode)
{
    // handle method call com.iflytek.aiservice.session.createSession
    //return static_cast<YourObjectType *>(parent())->createSession(appId, ability, errorcode);
}

int SessionAdaptor::freeSession(const QString &appId, const QString &ability)
{
    // handle method call com.iflytek.aiservice.session.freeSession
    int errorcode;
    QMetaObject::invokeMethod(parent(), "freeSession", Q_RETURN_ARG(int, errorcode), Q_ARG(QString, appId), Q_ARG(QString, ability));
    return errorcode;
}

