/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.daemon.Fprintd.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.FprintdAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Fprintd.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_DAEMON_FPRINTDADAPTOR_H
#define COM_DEEPIN_DAEMON_FPRINTDADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.Fprintd.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.daemon.Fprintd
 */
class FprintdAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.daemon.Fprintd")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.daemon.Fprintd\">\n"
"    <method name=\"GetDefaultDevice\">\n"
"      <arg direction=\"out\" type=\"o\"/>\n"
"    </method>\n"
"    <method name=\"GetDevices\">\n"
"      <arg direction=\"out\" type=\"ao\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"ao\" name=\"Devices\"/>\n"
"  </interface>\n"
        "")
public:
    FprintdAdaptor(QObject *parent);
    virtual ~FprintdAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QList<QDBusObjectPath> Devices READ devices)
    QList<QDBusObjectPath> devices() const;

public Q_SLOTS: // METHODS
    QDBusObjectPath GetDefaultDevice();
    QList<QDBusObjectPath> GetDevices();
Q_SIGNALS: // SIGNALS
};

#endif
