/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.iflytek.aiservice.tts.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.ttsAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.tts.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.iflytek.aiservice.ttsAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class TtsAdaptor
 */

TtsAdaptor::TtsAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

TtsAdaptor::~TtsAdaptor()
{
    // destructor
}

QString TtsAdaptor::putText(const QString &text)
{
    // handle method call com.iflytek.aiservice.tts.putText
    QString code;
    QMetaObject::invokeMethod(parent(), "putText", Q_RETURN_ARG(QString, code), Q_ARG(QString, text));
    return code;
}

QString TtsAdaptor::startCompose(const QVariantMap &params)
{
    // handle method call com.iflytek.aiservice.tts.startCompose
    QString sessionId;
    QMetaObject::invokeMethod(parent(), "startCompose", Q_RETURN_ARG(QString, sessionId), Q_ARG(QVariantMap, params));
    return sessionId;
}

QString TtsAdaptor::stopCompose()
{
    // handle method call com.iflytek.aiservice.tts.stopCompose
    QString code;
    QMetaObject::invokeMethod(parent(), "stopCompose", Q_RETURN_ARG(QString, code));
    return code;
}

