/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.lastore.Job.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.lastore.JobAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.lastore.Job.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_LASTORE_JOBADAPTOR_H
#define COM_DEEPIN_LASTORE_JOBADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.lastore.Job.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.lastore.Job
 */
class JobAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.lastore.Job")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.lastore.Job\">\n"
"    <signal name=\"Notify\">\n"
"      <arg type=\"i\"/>\n"
"    </signal>\n"
"    <property access=\"read\" type=\"s\" name=\"Id\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Name\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"PackageId\"/>\n"
"    <property access=\"read\" type=\"x\" name=\"CreateTime\"/>\n"
"    <property access=\"read\" type=\"x\" name=\"Speed\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Type\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Status\"/>\n"
"    <property access=\"read\" type=\"d\" name=\"Progress\"/>\n"
"    <property access=\"read\" type=\"s\" name=\"Description\"/>\n"
"    <property access=\"read\" type=\"i\" name=\"ElapsedTime\"/>\n"
"    <property access=\"read\" type=\"b\" name=\"Cancelable\"/>\n"
"    <property access=\"read\" type=\"as\" name=\"Packages\"/>\n"
"  </interface>\n"
        "")
public:
    JobAdaptor(QObject *parent);
    virtual ~JobAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool Cancelable READ cancelable)
    bool cancelable() const;

    Q_PROPERTY(qlonglong CreateTime READ createTime)
    qlonglong createTime() const;

    Q_PROPERTY(QString Description READ description)
    QString description() const;

    Q_PROPERTY(int ElapsedTime READ elapsedTime)
    int elapsedTime() const;

    Q_PROPERTY(QString Id READ id)
    QString id() const;

    Q_PROPERTY(QString Name READ name)
    QString name() const;

    Q_PROPERTY(QString PackageId READ packageId)
    QString packageId() const;

    Q_PROPERTY(QStringList Packages READ packages)
    QStringList packages() const;

    Q_PROPERTY(double Progress READ progress)
    double progress() const;

    Q_PROPERTY(qlonglong Speed READ speed)
    qlonglong speed() const;

    Q_PROPERTY(QString Status READ status)
    QString status() const;

    Q_PROPERTY(QString Type READ type)
    QString type() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
    void Notify(int in0);
};

#endif
