/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.daemon.ImageBlur.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.ImageBlurAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.ImageBlur.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.daemon.ImageBlurAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ImageBlurAdaptor
 */

ImageBlurAdaptor::ImageBlurAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ImageBlurAdaptor::~ImageBlurAdaptor()
{
    // destructor
}

QString ImageBlurAdaptor::Get(const QString &in0)
{
    // handle method call com.deepin.daemon.ImageBlur.Get
    QString out0;
    QMetaObject::invokeMethod(parent(), "Get", Q_RETURN_ARG(QString, out0), Q_ARG(QString, in0));
    return out0;
}

