/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.lastore.Smartmirror.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.lastore.SmartmirrorAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.lastore.Smartmirror.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_LASTORE_SMARTMIRRORADAPTOR_H
#define COM_DEEPIN_LASTORE_SMARTMIRRORADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.lastore.Smartmirror.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.lastore.Smartmirror
 */
class SmartmirrorAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.lastore.Smartmirror")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.lastore.Smartmirror\">\n"
"    <method name=\"Query\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"origin\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"official\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"url\"/>\n"
"    </method>\n"
"    <method name=\"SetEnable\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"enable\"/>\n"
"    </method>\n"
"    <property access=\"read\" type=\"b\" name=\"Enable\"/>\n"
"  </interface>\n"
        "")
public:
    SmartmirrorAdaptor(QObject *parent);
    virtual ~SmartmirrorAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool Enable READ enable)
    bool enable() const;

public Q_SLOTS: // METHODS
    QString Query(const QString &origin, const QString &official);
    void SetEnable(bool enable);
Q_SIGNALS: // SIGNALS
};

#endif
