/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.api.XEventMonitor.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.api.XEventMonitorAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.api.XEventMonitor.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.api.XEventMonitorAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class XEventMonitorAdaptor
 */

XEventMonitorAdaptor::XEventMonitorAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

XEventMonitorAdaptor::~XEventMonitorAdaptor()
{
    // destructor
}

QString XEventMonitorAdaptor::RegisterArea(int in0, int in1, int in2, int in3, int in4)
{
    // handle method call com.deepin.api.XEventMonitor.RegisterArea
    QString out0;
    QMetaObject::invokeMethod(parent(), "RegisterArea", Q_RETURN_ARG(QString, out0), Q_ARG(int, in0), Q_ARG(int, in1), Q_ARG(int, in2), Q_ARG(int, in3), Q_ARG(int, in4));
    return out0;
}

QString XEventMonitorAdaptor::RegisterAreas(AreaList in0, int in1)
{
    // handle method call com.deepin.api.XEventMonitor.RegisterAreas
    QString out0;
    QMetaObject::invokeMethod(parent(), "RegisterAreas", Q_RETURN_ARG(QString, out0), Q_ARG(AreaList, in0), Q_ARG(int, in1));
    return out0;
}

QString XEventMonitorAdaptor::RegisterFullScreen()
{
    // handle method call com.deepin.api.XEventMonitor.RegisterFullScreen
    QString out0;
    QMetaObject::invokeMethod(parent(), "RegisterFullScreen", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool XEventMonitorAdaptor::UnregisterArea(const QString &in0)
{
    // handle method call com.deepin.api.XEventMonitor.UnregisterArea
    bool out0;
    QMetaObject::invokeMethod(parent(), "UnregisterArea", Q_RETURN_ARG(bool, out0), Q_ARG(QString, in0));
    return out0;
}

