/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.AppStore.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.AppStoreAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.AppStore.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef COM_DEEPIN_APPSTOREADAPTOR_H
#define COM_DEEPIN_APPSTOREADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.AppStore.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface com.deepin.AppStore
 */
class AppStoreAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.deepin.AppStore")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.deepin.AppStore\">\n"
"    <method name=\"Raise\"/>\n"
"    <method name=\"AppDetails\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appID\"/>\n"
"    </method>\n"
"    <method name=\"ShowAppDetail\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"appName\"/>\n"
"    </method>\n"
"    <method name=\"Install\">\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"appID\"/>\n"
"    </method>\n"
"    <method name=\"Update\">\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"appID\"/>\n"
"    </method>\n"
"    <method name=\"UpdateAll\">\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"    </method>\n"
"    <method name=\"Uninstall\">\n"
"      <arg direction=\"out\" type=\"a{sv}\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"appID\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AppStoreAdaptor(QObject *parent);
    virtual ~AppStoreAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void AppDetails(const QString &appID);
    QVariantMap Install(const QString &appID);
    void Raise();
    void ShowAppDetail(const QString &appName);
    QVariantMap Uninstall(const QString &appID);
    QVariantMap Update(const QString &appID);
    QVariantMap UpdateAll();
Q_SIGNALS: // SIGNALS
};

#endif
