/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/com.deepin.appstore.Metadata.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.appstore.MetadataAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.appstore.Metadata.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/com.deepin.appstore.MetadataAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AppStoreAdaptor
 */

AppStoreAdaptor::AppStoreAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AppStoreAdaptor::~AppStoreAdaptor()
{
    // destructor
}

QString AppStoreAdaptor::GetAppIcon(const QString &app_name)
{
    // handle method call com.deepin.AppStore.GetAppIcon
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetAppIcon", Q_RETURN_ARG(QString, out0), Q_ARG(QString, app_name));
    return out0;
}

QString AppStoreAdaptor::GetAppMetadataList(const QStringList &app_name_list)
{
    // handle method call com.deepin.AppStore.GetAppMetadataList
    QString out0;
    QMetaObject::invokeMethod(parent(), "GetAppMetadataList", Q_RETURN_ARG(QString, out0), Q_ARG(QStringList, app_name_list));
    return out0;
}

void AppStoreAdaptor::OpenApp(const QString &app_name)
{
    // handle method call com.deepin.AppStore.OpenApp
    QMetaObject::invokeMethod(parent(), "OpenApp", Q_ARG(QString, app_name));
}

