/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/org.bluez.obex.AgentManager1.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.AgentManager1Adaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.AgentManager1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.AgentManager1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class AgentManager1Adaptor
 */

AgentManager1Adaptor::AgentManager1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

AgentManager1Adaptor::~AgentManager1Adaptor()
{
    // destructor
}

void AgentManager1Adaptor::RegisterAgent(const QDBusObjectPath &agent)
{
    // handle method call org.bluez.obex.AgentManager1.RegisterAgent
    QMetaObject::invokeMethod(parent(), "RegisterAgent", Q_ARG(QDBusObjectPath, agent));
}

void AgentManager1Adaptor::UnregisterAgent(const QDBusObjectPath &agent)
{
    // handle method call org.bluez.obex.AgentManager1.UnregisterAgent
    QMetaObject::invokeMethod(parent(), "UnregisterAgent", Q_ARG(QDBusObjectPath, agent));
}

