/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/org.bluez.obex.Client1.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.Client1Adaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.Client1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_BLUEZ_OBEX_CLIENT1ADAPTOR_H
#define ORG_BLUEZ_OBEX_CLIENT1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.Client1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.bluez.obex.Client1
 */
class Client1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.bluez.obex.Client1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.bluez.obex.Client1\">\n"
"    <method name=\"CreateSession\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"destination\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"args\"/>\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"out\" type=\"o\" name=\"session\"/>\n"
"    </method>\n"
"    <method name=\"RemoveSession\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"session\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    Client1Adaptor(QObject *parent);
    virtual ~Client1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QDBusObjectPath CreateSession(const QString &destination, const QVariantMap &args);
    void RemoveSession(const QDBusObjectPath &session);
Q_SIGNALS: // SIGNALS
};

#endif
