/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/org.freedesktop.DisplayManager.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.freedesktop.DisplayManagerAdaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.freedesktop.DisplayManager.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.freedesktop.DisplayManagerAdaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DisplayManagerAdaptor
 */

DisplayManagerAdaptor::DisplayManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DisplayManagerAdaptor::~DisplayManagerAdaptor()
{
    // destructor
}

QList<QDBusObjectPath> DisplayManagerAdaptor::seats() const
{
    // get the value of property Seats
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Seats"));
}

QList<QDBusObjectPath> DisplayManagerAdaptor::sessions() const
{
    // get the value of property Sessions
    return qvariant_cast< QList<QDBusObjectPath> >(parent()->property("Sessions"));
}

QDBusObjectPath DisplayManagerAdaptor::AddLocalXSeat(int display_number)
{
    // handle method call org.freedesktop.DisplayManager.AddLocalXSeat
    QDBusObjectPath seat;
    QMetaObject::invokeMethod(parent(), "AddLocalXSeat", Q_RETURN_ARG(QDBusObjectPath, seat), Q_ARG(int, display_number));
    return seat;
}

QDBusObjectPath DisplayManagerAdaptor::AddSeat(const QString &type, PropertyList properties)
{
    // handle method call org.freedesktop.DisplayManager.AddSeat
    QDBusObjectPath seat;
    QMetaObject::invokeMethod(parent(), "AddSeat", Q_RETURN_ARG(QDBusObjectPath, seat), Q_ARG(QString, type), Q_ARG(PropertyList, properties));
    return seat;
}

