/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/org.freedesktop.Hostname1.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.freedesktop.Hostname1Adaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.freedesktop.Hostname1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.freedesktop.Hostname1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Hostname1Adaptor
 */

Hostname1Adaptor::Hostname1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Hostname1Adaptor::~Hostname1Adaptor()
{
    // destructor
}

QString Hostname1Adaptor::staticHostname() const
{
    // get the value of property StaticHostname
    return qvariant_cast< QString >(parent()->property("StaticHostname"));
}

void Hostname1Adaptor::SetStaticHostname(const QString &in0, bool in1)
{
    // handle method call org.freedesktop.hostname1.SetStaticHostname
    QMetaObject::invokeMethod(parent(), "SetStaticHostname", Q_ARG(QString, in0), Q_ARG(bool, in1));
}

