/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/org.bluez.obex.Session1.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.Session1Adaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.Session1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.Session1Adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class Session1Adaptor
 */

Session1Adaptor::Session1Adaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

Session1Adaptor::~Session1Adaptor()
{
    // destructor
}

uchar Session1Adaptor::channel() const
{
    // get the value of property Channel
    return qvariant_cast< uchar >(parent()->property("Channel"));
}

QString Session1Adaptor::destination() const
{
    // get the value of property Destination
    return qvariant_cast< QString >(parent()->property("Destination"));
}

QString Session1Adaptor::source() const
{
    // get the value of property Source
    return qvariant_cast< QString >(parent()->property("Source"));
}

QString Session1Adaptor::target() const
{
    // get the value of property Target
    return qvariant_cast< QString >(parent()->property("Target"));
}

QString Session1Adaptor::GetCapabilities()
{
    // handle method call org.bluez.obex.Session1.GetCapabilities
    QString capabilities;
    QMetaObject::invokeMethod(parent(), "GetCapabilities", Q_RETURN_ARG(QString, capabilities));
    return capabilities;
}

