/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp ./dde-qt-dbus-factory/xml/org.bluez.obex.AgentManager1.xml -a ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.AgentManager1Adaptor -i ./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.AgentManager1.h
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef ORG_BLUEZ_OBEX_AGENTMANAGER1ADAPTOR_H
#define ORG_BLUEZ_OBEX_AGENTMANAGER1ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "./dde-qt-dbus-factory/toolGenerate/qdbusxml2cpp/org.bluez.obex.AgentManager1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.bluez.obex.AgentManager1
 */
class AgentManager1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.bluez.obex.AgentManager1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.bluez.obex.AgentManager1\">\n"
"    <method name=\"RegisterAgent\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"agent\"/>\n"
"    </method>\n"
"    <method name=\"UnregisterAgent\">\n"
"      <arg direction=\"in\" type=\"o\" name=\"agent\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    AgentManager1Adaptor(QObject *parent);
    virtual ~AgentManager1Adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void RegisterAgent(const QDBusObjectPath &agent);
    void UnregisterAgent(const QDBusObjectPath &agent);
Q_SIGNALS: // SIGNALS
};

#endif
